services:
  pdftopng:
    build: .
    container_name: pdftopng
    ports:
      - "8080:8080"
    read_only: false
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:size=100m
    restart: unless-stopped
